name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Snake animation generator
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: shaikyunus
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Optional: Remove .git in dist to avoid git push errors
      - name: Clean dist .git (if exists)
        run: rm -rf dist/.git

      # Push generated content to output branch
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Generate snake contribution graph"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
